#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: gVNS (ggfevans)
# License: MIT | https://github.com/community-scripts/ProxmoxVED/raw/main/LICENSE
# Source: https://github.com/RackulaLives/Rackula

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt install -y nginx
msg_ok "Installed Dependencies"

msg_info "Creating rackula user"
if ! id -u rackula >/dev/null 2>&1; then
  useradd --system --user-group --home-dir /opt/rackula --shell /usr/sbin/nologin rackula
fi
msg_ok "Created rackula user"

msg_info "Installing Bun"
ensure_dependencies unzip ca-certificates
BUN_VERSION="${BUN_VERSION:-1.3.14}"
case "$(uname -m)" in
  x86_64) grep -q avx2 /proc/cpuinfo && BUN_VARIANT="x64" || BUN_VARIANT="x64-baseline" ;;
  aarch64) BUN_VARIANT="aarch64" ;;
  *)
    msg_error "Unsupported architecture: $(uname -m)"
    exit 1
    ;;
esac
BUN_TMP=$(mktemp -d)
curl_with_retry "https://github.com/oven-sh/bun/releases/download/bun-v${BUN_VERSION}/bun-linux-${BUN_VARIANT}.zip" "$BUN_TMP/bun.zip"
$STD unzip -o "$BUN_TMP/bun.zip" -d "$BUN_TMP"
mkdir -p /usr/local/bun/bin
install -m 755 "$BUN_TMP/bun-linux-${BUN_VARIANT}/bun" /usr/local/bun/bin/bun
rm -rf "$BUN_TMP"
ln -sf /usr/local/bun/bin/bun /usr/local/bin/bun
ln -sf /usr/local/bun/bin/bun /usr/local/bin/bunx
[ -x /usr/local/bun/bin/bun ] || {
  msg_error "Bun installation failed"
  exit 1
}
msg_ok "Installed Bun"

# RACKULA_PREBUILD_TARBALL (dev/test only): when set to a local tarball, deploy that payload
# instead of fetching a published release. Inert when unset. See docs/deployment/LXC-TESTING.md.
if [[ -n "${RACKULA_PREBUILD_TARBALL:-}" ]]; then
  [[ -f "${RACKULA_PREBUILD_TARBALL}" ]] || {
    msg_error "RACKULA_PREBUILD_TARBALL set but file not found: ${RACKULA_PREBUILD_TARBALL}"
    exit 1
  }
  msg_info "Deploying dev prebuild (RACKULA_PREBUILD_TARBALL)"
  mkdir -p /opt/rackula
  tar --no-same-owner -xzf "$RACKULA_PREBUILD_TARBALL" -C /opt/rackula --strip-components=1
  msg_ok "Deployed dev prebuild"
else
  fetch_and_deploy_gh_release "rackula" "RackulaLives/Rackula" "prebuild" "latest" "/opt/rackula" "rackula-lxc-*.tar.gz"
fi

msg_info "Installing Rackula"
mkdir -p /opt/rackula/data
mkdir -p /etc/nginx/snippets

SECURITY_HEADERS_SRC="/opt/rackula/config/security-headers.conf"
if [ ! -f "$SECURITY_HEADERS_SRC" ]; then
  msg_error "Required config file missing: $SECURITY_HEADERS_SRC (release may be incomplete)"
  exit 1
fi
cp "$SECURITY_HEADERS_SRC" /etc/nginx/snippets/security-headers.conf

# Runtime storage mode config consumed by index.html. The LXC always
# provisions the API alongside the frontend, so server mode is fixed.
# CROSS-REF: keep in sync with ct/rackula.sh update_script and static/config.js.
printf 'window.__RACKULA_CONFIG__ = { storage: "server" };\n' >/opt/rackula/frontend/config.js

chown -R root:root /opt/rackula/frontend
find /opt/rackula/frontend -type d -exec chmod 755 {} \;
find /opt/rackula/frontend -type f -exec chmod 644 {} \;
chown -R rackula:rackula /opt/rackula/{api,data}
chmod 750 /opt/rackula/data
msg_ok "Installed Rackula"

msg_info "Generating API write token"
API_WRITE_TOKEN=$(openssl rand -hex 32)

CORS_SCHEME="${CORS_SCHEME:-http}"
case "$CORS_SCHEME" in
  http | https) ;;
  *)
    msg_error "Invalid CORS_SCHEME '${CORS_SCHEME}' (expected 'http' or 'https')"
    exit 1
    ;;
esac

ALLOW_INSECURE_CORS="${ALLOW_INSECURE_CORS:-false}"
case "$ALLOW_INSECURE_CORS" in
  true | false) ;;
  *)
    msg_error "Invalid ALLOW_INSECURE_CORS '${ALLOW_INSECURE_CORS}' (expected 'true' or 'false')"
    exit 1
    ;;
esac

cat <<EOF >/opt/rackula/data/.env
RACKULA_API_WRITE_TOKEN=${API_WRITE_TOKEN}
CORS_ORIGIN=${CORS_SCHEME}://localhost
ALLOW_INSECURE_CORS=${ALLOW_INSECURE_CORS}
EOF
chown rackula:rackula /opt/rackula/data/.env
chmod 600 /opt/rackula/data/.env

cat <<EOF >/etc/nginx/snippets/rackula-api-token.conf
# Auto-generated by rackula-install.sh, do not edit manually
# Defined as map (not set) because the snippet is included at http context.
map \$host \$rackula_api_write_token {
  default "${API_WRITE_TOKEN}";
}
map \$host \$rackula_has_api_write_token {
  default 1;
}
EOF
chown root:www-data /etc/nginx/snippets/rackula-api-token.conf
chmod 640 /etc/nginx/snippets/rackula-api-token.conf
msg_ok "Generated API write token"

msg_info "Configuring nginx"
cp /opt/rackula/config/nginx.conf /etc/nginx/sites-available/rackula
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/rackula /etc/nginx/sites-enabled/rackula
if ! $STD nginx -t; then
  msg_error "nginx configuration test failed (run 'nginx -t' for details)"
  exit 1
fi
msg_ok "Configured nginx"

msg_info "Creating Services"
cp /opt/rackula/config/rackula-api.service /etc/systemd/system/rackula-api.service
mkdir -p /etc/systemd/system/nginx.service.d
cp /opt/rackula/config/nginx.service.d-override.conf /etc/systemd/system/nginx.service.d/override.conf
systemctl daemon-reload
systemctl enable -q nginx rackula-api
systemctl restart nginx rackula-api
msg_ok "Created Services"

msg_info "Verifying Services"
for i in $(seq 0 9); do
  if curl -sf --connect-timeout 2 --max-time 5 http://127.0.0.1/api/health >/dev/null 2>&1; then
    msg_ok "Service running successfully"
    break
  fi
  sleep 1
  if [ "$i" -eq 9 ]; then
    msg_error "Service failed to respond on http://127.0.0.1/api/health within 10 seconds"
    exit 1
  fi
done

motd_ssh
customize
cleanup_lxc
