#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: gVNS
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
# Source: https://github.com/RackulaLives/Rackula

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt install -y \
  nginx \
  unzip \
  curl
msg_ok "Installed Dependencies"

msg_info "Installing Bun"
export BUN_INSTALL=/opt/bun
curl -fsSL https://bun.sh/install | $STD bash
if [ ! -f /opt/bun/bin/bun ]; then
  msg_error "Bun installation failed — binary not found at /opt/bun/bin/bun"
  exit 1
fi
ln -sf /opt/bun/bin/bun /usr/local/bin/bun
if [ -f /opt/bun/bin/bunx ]; then
  ln -sf /opt/bun/bin/bunx /usr/local/bin/bunx
else
  # bunx is typically bun with different argv[0]; fall back to symlink via bun
  ln -sf /usr/local/bin/bun /usr/local/bin/bunx
fi
msg_ok "Installed Bun"

msg_info "Creating rackula user"
if ! id -u rackula >/dev/null 2>&1; then
  useradd --system --user-group --home-dir /opt/rackula --shell /usr/sbin/nologin rackula
fi
msg_ok "Created rackula user"

msg_info "Installing Rackula"
fetch_and_deploy_gh_release "rackula" "RackulaLives/Rackula" "prebuild" "latest" "/opt/rackula" "rackula-lxc-*.tar.gz"

# Create persistent data directory (not in tarball)
mkdir -p /opt/rackula/data
mkdir -p /etc/nginx/snippets

# Deploy config files from the release
cp /opt/rackula/config/security-headers.conf /etc/nginx/snippets/security-headers.conf

# Set ownership: frontend root-owned (served by nginx), API rackula-owned
chown -R root:root /opt/rackula/frontend
find /opt/rackula/frontend -type d -exec chmod 755 {} \;
find /opt/rackula/frontend -type f -exec chmod 644 {} \;
chown -R rackula:rackula /opt/rackula/api
chown -R rackula:rackula /opt/rackula/data
chmod 750 /opt/rackula/data
msg_ok "Installed Rackula"

msg_info "Generating API write token"
API_WRITE_TOKEN=$(openssl rand -hex 32)

# CORS origin scheme — defaults to http. Behind an HTTPS reverse proxy, export
# CORS_SCHEME=https before running the installer, or edit CORS_ORIGIN in
# /opt/rackula/data/.env afterwards and restart rackula-api. Only http/https
# are accepted; anything else is rejected to avoid writing a malformed origin.
CORS_SCHEME="${CORS_SCHEME:-http}"
case "$CORS_SCHEME" in
  http | https) ;;
  *)
    msg_error "Invalid CORS_SCHEME '${CORS_SCHEME}' (expected 'http' or 'https')"
    exit 1
    ;;
esac

# Insecure CORS is disabled by default. Set ALLOW_INSECURE_CORS=true explicitly
# before running installer only when required by your deployment.
ALLOW_INSECURE_CORS="${ALLOW_INSECURE_CORS:-false}"
case "$ALLOW_INSECURE_CORS" in
  true | false) ;;
  *)
    msg_error "Invalid ALLOW_INSECURE_CORS '${ALLOW_INSECURE_CORS}' (expected 'true' or 'false')"
    exit 1
    ;;
esac

# Write API environment file
cat <<EOF >/opt/rackula/data/.env
RACKULA_API_WRITE_TOKEN=${API_WRITE_TOKEN}
CORS_ORIGIN=${CORS_SCHEME}://localhost
ALLOW_INSECURE_CORS=${ALLOW_INSECURE_CORS}
EOF
chown rackula:rackula /opt/rackula/data/.env
chmod 600 /opt/rackula/data/.env

# Write nginx token snippet (included by nginx.conf)
cat <<EOF >/etc/nginx/snippets/rackula-api-token.conf
# Auto-generated by rackula-install.sh — do not edit manually
set \$rackula_api_write_token "${API_WRITE_TOKEN}";
set \$rackula_has_api_write_token 1;
EOF
chmod 600 /etc/nginx/snippets/rackula-api-token.conf
msg_ok "Generated API write token"

msg_info "Configuring nginx"

# Deploy rackula nginx site config from the packaged tarball (single source of truth)
cp /opt/rackula/config/nginx.conf /etc/nginx/sites-available/rackula

# Remove default site, enable rackula
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/rackula /etc/nginx/sites-enabled/rackula
msg_ok "Configured nginx"

msg_info "Creating Services"
# Deploy the hardened API unit from the packaged tarball (single source of truth)
cp /opt/rackula/config/rackula-api.service /etc/systemd/system/rackula-api.service

# Harden nginx service via drop-in override (copy from packaged config)
mkdir -p /etc/systemd/system/nginx.service.d
cp /opt/rackula/config/nginx.service.d-override.conf /etc/systemd/system/nginx.service.d/override.conf

systemctl daemon-reload
systemctl enable -q --now rackula-api
systemctl enable -q --now nginx
msg_ok "Created Services"

msg_info "Verifying Services"
for i in $(seq 1 10); do
  if curl -sf --connect-timeout 2 --max-time 5 http://127.0.0.1:3001/health >/dev/null 2>&1; then
    msg_ok "Service running successfully"
    break
  fi
  if [ "$i" -eq 10 ]; then
    msg_error "API failed to start within 10 seconds"
    exit 1
  fi
  sleep 1
done

motd_ssh
customize
cleanup_lxc