/**
 * Brand Asset Generation Script
 * Generates all logo SVGs and rasters from the canonical geometry in
 * src/lib/components/logo-geometry.ts.
 *
 * Outputs:
 * - static/brand/logo-mark*.svg (tight box, colour variants, square variant)
 * - static/brand/logo-mark-{16..512}.png
 * - static/favicon.svg, favicon-light.svg, favicon.png, favicon-light.png
 * - static/apple-touch-icon.png (180x180 on Dracula background)
 * - static/favicon.ico + static/brand/favicon.ico (requires ImageMagick)
 *
 * Usage: npm run generate-brand-assets
 */
import sharp from "sharp";
import { spawnSync } from "child_process";
import { writeFile, copyFile, mkdtemp, rm } from "fs/promises";
import { tmpdir } from "os";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  LOGO_PATH,
  LOGO_VIEWBOX,
  LOGO_SQUARE_VIEWBOX,
} from "../src/lib/components/logo-geometry";
import { draculaColors, alucardColors } from "../src/lib/utils/contrast";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BRAND = join(ROOT, "static", "brand");
const STATIC = join(ROOT, "static");

const DRACULA_PURPLE = draculaColors.purple;
const ALUCARD_PURPLE = alucardColors.purple;
const DRACULA_BG = draculaColors.bg;

const PNG_SIZES = [16, 32, 48, 64, 128, 192, 256, 512];
// Legacy /favicon.ico fallback only; modern browsers use the SVG/PNG links.
// Larger entries are stored as uncompressed BMPs and bloat the file.
const ICO_SIZES = [16, 32, 48];

const GENERATED_NOTE =
  "<!-- Generated by scripts/generate-brand-assets.ts. Do not edit by hand. -->";

function markSvg(viewBox: string, fill: string, size?: number): string {
  const dimensions = size ? ` width="${size}" height="${size}"` : "";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}"${dimensions}>`,
    `  ${GENERATED_NOTE}`,
    `  <path d="${LOGO_PATH}" fill="${fill}" fill-rule="evenodd"/>`,
    "</svg>",
    "",
  ].join("\n");
}

async function writeSvgs(): Promise<void> {
  const svgs: Array<[string, string]> = [
    [join(BRAND, "logo-mark.svg"), markSvg(LOGO_VIEWBOX, DRACULA_PURPLE)],
    [
      join(BRAND, "logo-mark-alucard.svg"),
      markSvg(LOGO_VIEWBOX, ALUCARD_PURPLE),
    ],
    [join(BRAND, "logo-mark-mono-black.svg"), markSvg(LOGO_VIEWBOX, "#000000")],
    [join(BRAND, "logo-mark-mono-white.svg"), markSvg(LOGO_VIEWBOX, "#FFFFFF")],
    [
      join(BRAND, "logo-mark-square.svg"),
      markSvg(LOGO_SQUARE_VIEWBOX, DRACULA_PURPLE),
    ],
    [join(STATIC, "favicon.svg"), markSvg(LOGO_SQUARE_VIEWBOX, DRACULA_PURPLE)],
    [
      join(STATIC, "favicon-light.svg"),
      markSvg(LOGO_SQUARE_VIEWBOX, ALUCARD_PURPLE),
    ],
  ];
  for (const [path, content] of svgs) {
    await writeFile(path, content);
    console.log(`wrote ${path}`);
  }
}

function squarePng(fill: string, size: number): Promise<Buffer> {
  return sharp(Buffer.from(markSvg(LOGO_SQUARE_VIEWBOX, fill, size)))
    .png()
    .toBuffer();
}

async function writePngs(): Promise<void> {
  for (const size of PNG_SIZES) {
    const path = join(BRAND, `logo-mark-${size}.png`);
    await writeFile(path, await squarePng(DRACULA_PURPLE, size));
    console.log(`wrote ${path}`);
  }

  await writeFile(
    join(STATIC, "favicon.png"),
    await squarePng(DRACULA_PURPLE, 32),
  );
  await writeFile(
    join(STATIC, "favicon-light.png"),
    await squarePng(ALUCARD_PURPLE, 32),
  );
  console.log("wrote favicon.png, favicon-light.png");

  const mark = await squarePng(DRACULA_PURPLE, 132);
  const touchIcon = await sharp({
    create: { width: 180, height: 180, channels: 4, background: DRACULA_BG },
  })
    .composite([{ input: mark, top: 24, left: 24 }])
    .png()
    .toBuffer();
  await writeFile(join(STATIC, "apple-touch-icon.png"), touchIcon);
  console.log("wrote apple-touch-icon.png");
}

async function writeIco(): Promise<void> {
  const magick = spawnSync("magick", ["-version"], { stdio: "ignore" });
  if (magick.error) {
    console.warn("skipped favicon.ico: ImageMagick (magick) not found on PATH");
    return;
  }

  const tmp = await mkdtemp(join(tmpdir(), "rackula-ico-"));
  try {
    const inputs: string[] = [];
    for (const size of ICO_SIZES) {
      const path = join(tmp, `${size}.png`);
      await writeFile(path, await squarePng(DRACULA_PURPLE, size));
      inputs.push(path);
    }
    const icoPath = join(STATIC, "favicon.ico");
    const result = spawnSync("magick", [...inputs, icoPath], {
      stdio: "inherit",
    });
    if (result.status !== 0) {
      throw new Error(`magick exited with status ${result.status}`);
    }
    await copyFile(icoPath, join(BRAND, "favicon.ico"));
    console.log("wrote favicon.ico (static + brand)");
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

await writeSvgs();
await writePngs();
await writeIco();
console.log("done");
